public  class SalesforceDeveloper {
    public void myFirstCode(){
        system.debug('My favorite city is Izmir');
        system.debug('My favorite film is pianist');
        system.debug('my favorite season is spring');

    }
    public void myFavorites(){
    string mycity ='Dallas';
    System.debug(mycity);
    integer fn=33;
    System.debug(fn);
    string  text='favori numaram-> '+fn+' bulundugum sehir-> '+mycity;
    System.debug(text);

    }
  

}