public  class ArthimaticCalculations {
    public integer  addition(integer x,integer y) {
        integer z=x+y;
        return z;

    }
    public integer  subtraction(integer x,integer y) {
        integer z=x-y;
        return z;
    }

    public integer  multiplication(integer w,integer x,integer y) {
        integer z=x*y*w;
        return z;
    }
    public  string concatString(string a,string b){
        string z=a+' & '+b;
        return z;
    }



}