public  class CheckDatatypes {

public void methodBoolean(){
    boolean checkBoolean=true;
    system.debug(checkBoolean);
}
public void methodInteger(){
    integer varfirst=1;
    integer varsecond=2;
    system.debug(varfirst);
    system.debug(varsecond);

}

public void stringMethod(){
    string varname='Name';
    string var2name='your name';

    system.debug(varname);
    system.debug(var2name);
}



public void methodId(){
id checkId='0013x00002RfRdAAAV';
system.debug(checkId);
}
public void  methodDouble(){
Decimal varfirst2=1.23;
Double   varsecond2=209.764;
system.debug(varfirst2);
system.debug(varsecond2);


}







}