ListDemo2.iterateListString99();
list<string> ls1 =new list<string>{'list','set','map','array'};
system.debug(ListDemo2.add(ls1));



ListDemo2.iterateList();
List<integer>templist=new List<integer>{5,21,15,99,77,101};
integer sum1=ListDemo2.add(templist);
system.debug('sum1 is '+sum1);

ListDemo2.add(templist);


list<string> ls =new list<string>{'list','set','map','array'};
ls.add('methods');
ls.add('constructor');
ListDemo2.iterateListString(ls);