




Set<String>colors=new Set<String>{'red','black','white','gray','green'};
Set<String> colorsIncaps=SetDemo.upperCaseSet(colors);
system.debug(colorsIncaps);







Set<Integer> ns=new Set<Integer>();
ns.add(10);
system.debug(ns);




SetDemo.setFromList();



setDemo.citySet();





SetDemo.randomIntegerSet();

set<boolean> bs = new set<boolean>();
bs.add(true);
bs.add(false);
bs.add(null);
bs.add(true);
bs.add(false);
bs.add(null);
system.debug(bs);


